export const cards = [
  [
    {
      id: 0,
      name: 'Action (set A)',
      image: 'images/dance.jpg',
    },
    {
      id: 1,
      name: 'Action (set B)',
      image: 'images/play.jpg',
    },
    {
      id: 2,
      name: 'Animal (set A)',
      image: 'images/cat.jpg',
    },
    {
      id: 3,
      name: 'Animal (set B)',
      image: 'images/lion.jpg',
    },
    {
      id: 4,
      name: 'Clothes',
      image: 'images/skirt.jpg',
    },
    {
      id: 5,
      name: 'Emotions',
      image: 'images/tired.jpg',
    },
    {
      id: 6,
      name: 'Professions',
      image: 'images/biolog.jpeg',
    },
    {
      id: 7,
      name: 'Food',
      image: 'images/Klubnika.jpg',
    },
  ],
  [
    {
      word: 'cry',
      translation: 'плакать',
      image: 'images/cry.jpg',
      audioSrc: 'audio/cry.mp3',
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: 'images/dance.jpg',
      audioSrc: 'audio/dance.mp3',
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: 'images/dive.jpg',
      audioSrc: 'audio/dive.mp3',
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: 'images/draw.jpg',
      audioSrc: 'audio/draw.mp3',
    },
    {
      word: 'fishing',
      translation: 'ловить рыбу',
      image: 'images/fish.jpg',
      audioSrc: 'audio/fishing.mp3',
    },
    {
      word: 'fly',
      translation: 'летать',
      image: 'images/fly.jpg',
      audioSrc: 'audio/fly.mp3',
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: 'images/hug.jpg',
      audioSrc: 'audio/hug.mp3',
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: 'images/jump.jpg',
      audioSrc: 'audio/jump.mp3',
    },
  ],
  [
    {
      word: 'open',
      translation: 'открывать',
      image: 'images/open.jpg',
      audioSrc: 'audio/open.mp3',
    },
    {
      word: 'play',
      translation: 'играть',
      image: 'images/play.jpg',
      audioSrc: 'audio/play.mp3',
    },
    {
      word: 'point',
      translation: 'указывать',
      image: 'images/point.jpg',
      audioSrc: 'audio/point.mp3',
    },
    {
      word: 'ride',
      translation: 'ездить',
      image: 'images/ride.jpg',
      audioSrc: 'audio/ride.mp3',
    },
    {
      word: 'run',
      translation: 'бегать',
      image: 'images/run.jpg',
      audioSrc: 'audio/run.mp3',
    },
    {
      word: 'sing',
      translation: 'петь',
      image: 'images/sing.jpg',
      audioSrc: 'audio/sing.mp3',
    },
    {
      word: 'skip',
      translation: 'пропускать, прыгать',
      image: 'images/skip.jpg',
      audioSrc: 'audio/skip.mp3',
    },
    {
      word: 'swim',
      translation: 'плавать',
      image: 'images/swim.jpg',
      audioSrc: 'audio/swim.mp3',
    },
  ],
  [
    {
      word: 'cat',
      translation: 'кот',
      image: 'images/cat.jpg',
      audioSrc: 'audio/cat.mp3',
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      image: 'images/chick.jpg',
      audioSrc: 'audio/chick.mp3',
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: 'images/chicken.jpg',
      audioSrc: 'audio/chicken.mp3',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: 'images/dog.jpg',
      audioSrc: 'audio/dog.mp3',
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: 'images/horse.jpg',
      audioSrc: 'audio/horse.mp3',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: 'images/pig.jpg',
      audioSrc: 'audio/pig.mp3',
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: 'images/rabbit.jpg',
      audioSrc: 'audio/rabbit.mp3',
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: 'images/sheep.jpg',
      audioSrc: 'audio/sheep.mp3',
    },
  ],
  [
    {
      word: 'bird',
      translation: 'птица',
      image: 'images/bird.jpg',
      audioSrc: 'audio/bird.mp3',
    },
    {
      word: 'fish',
      translation: 'рыба',
      image: 'images/fish1.jpg',
      audioSrc: 'audio/fish.mp3',
    },
    {
      word: 'frog',
      translation: 'жаба',
      image: 'images/frog.jpg',
      audioSrc: 'audio/frog.mp3',
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      image: 'images/giraffe.jpg',
      audioSrc: 'audio/giraffe.mp3',
    },
    {
      word: 'lion',
      translation: 'лев',
      image: 'images/lion.jpg',
      audioSrc: 'audio/lion.mp3',
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: 'images/mouse.jpg',
      audioSrc: 'audio/mouse.mp3',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: 'images/turtle.jpg',
      audioSrc: 'audio/turtle.mp3',
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: 'images/dolphin.jpg',
      audioSrc: 'audio/dolphin.mp3',
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      image: 'images/skirt.jpg',
      audioSrc: 'audio/skirt.mp3',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: 'images/pants.jpg',
      audioSrc: 'audio/pants.mp3',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: 'images/blouse.jpg',
      audioSrc: 'audio/blouse.mp3',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: 'images/dress.jpg',
      audioSrc: 'audio/dress.mp3',
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: 'images/boot.jpg',
      audioSrc: 'audio/boot.mp3',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: 'images/shirt.jpg',
      audioSrc: 'audio/shirt.mp3',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: 'images/coat.jpg',
      audioSrc: 'audio/coat.mp3',
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: 'images/shoe.jpg',
      audioSrc: 'audio/shoe.mp3',
    },
  ],
  [
    {
      word: 'sad',
      translation: 'грустный',
      image: 'images/sad.jpg',
      audioSrc: 'audio/sad.mp3',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: 'images/angry.jpg',
      audioSrc: 'audio/angry.mp3',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: 'images/happy.jpg',
      audioSrc: 'audio/happy.mp3',
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: 'images/tired.jpg',
      audioSrc: 'audio/tired.mp3',
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: 'images/surprised.jpg',
      audioSrc: 'audio/surprised.mp3',
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: 'images/scared.jpg',
      audioSrc: 'audio/scared.mp3',
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: 'images/smile.jpg',
      audioSrc: 'audio/smile.mp3',
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: 'images/laugh.jpg',
      audioSrc: 'audio/laugh.mp3',
    },
  ],
  [
    {
      word: 'doctor',
      translation: 'врач',
      image: 'images/doctor1.jpg',
      audioSrc: 'audio/doctor.mp3',
    },
    {
      word: 'biologist',
      translation: 'биолог',
      image: 'images/biolog.jpg',
      audioSrc: 'audio/biologist.mp3',
    },
    {
      word: 'accountant',
      translation: 'бухгалтер',
      image: 'images/manager.jpg',
      audioSrc: 'audio/accountant.mp3',
    },
    {
      word: 'programmer',
      translation: 'программист',
      image: 'images/programmer.jpg',
      audioSrc: 'audio/programmer.mp3',
    },
    {
      word: 'cook',
      translation: 'повар',
      image: 'images/povar1.jpg',
      audioSrc: 'audio/cook.mp3',
    },
    {
      word: 'mechanic',
      translation: 'механик',
      image: 'images/mechanik.jpg',
      audioSrc: 'audio/mechanic.mp3',
    },
    {
      word: 'teacher',
      translation: 'учитель',
      image: 'images/teacher.jpg',
      audioSrc: 'audio/teacher.mp3',
    },
    {
      word: 'astronaut',
      translation: 'астронавт',
      image: 'images/cosmonavt.jpg',
      audioSrc: 'audio/astronaut.mp3',
    },
  ],
  [
    {
      word: 'apple',
      translation: 'яблоко',
      image: 'images/apple.jpg',
      audioSrc: 'audio/apple.mp3',
    },
    {
      word: 'banana',
      translation: 'банан',
      image: 'images/banane.jpg',
      audioSrc: 'audio/banana.mp3',
    },
    {
      word: 'carrot',
      translation: 'морковь',
      image: 'images/CarrotRoots.jpg',
      audioSrc: 'audio/carrot.mp3',
    },
    {
      word: 'strawberry',
      translation: 'клубника',
      image: 'images/Klubnika.jpg',
      audioSrc: 'audio/strawberry.mp3',
    },
    {
      word: 'orange',
      translation: 'апельсин',
      image: 'images/orange.jpg',
      audioSrc: 'audio/orange.mp3',
    },
    {
      word: 'grapes',
      translation: 'виноград',
      image: 'images/vinograd.jpg',
      audioSrc: 'audio/grapes.mp3',
    },
    {
      word: 'cabbage',
      translation: 'капуста',
      image: 'images/kapusta-01.jpg',
      audioSrc: 'audio/cabbage.mp3',
    },
    {
      word: 'potato',
      translation: 'картофель',
      image: 'images/potato.jpg',
      audioSrc: 'audio/potato.mp3',
    },
  ],
];


export default cards;
